# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [240]:
#Write your code here
import pandas as pd

df_data = pd.read_csv('Data/Purchase_Data.csv')
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [241]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

In [242]:
#Write you code here
result_1 = df_data.loc[:, df_data.columns[0:2]]
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [243]:
#Write you code here
result_2 = df_data.loc[0:1]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [244]:
#Write your code here
result_3 = df_data.loc[:3, df_data.columns[0:5]]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [245]:
#Write your code here
result_4 = df_data.loc[[0,4,6], ["invoice_time", "price"]]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [246]:
num_rows = df_data.shape[0]
num_rows
#df.shape

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [247]:
#Write your code here
df_data.iloc[[num_rows - 1]]

#df.tail(1)

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [248]:
#Write your code here
avg_price, max_price = df_data['price'].mean(), df_data['price'].max()
print(f'avg_price:{avg_price:.2f}, max_price:{max_price}')

avg_price:3.19, max_price:6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [249]:
#Write you code here
avg_price, avg_num_items = df_data[['price', 'num_item']].mean()
print(f'avg_price:{avg_price:.2f}, avg_num_items:{avg_num_items:.2f}')

avg_price:3.19, avg_num_items:1.30

Create a column called "total", which is the product of the price and num_item columns.

In [250]:
#Write your code here
df_data['total'] = df_data['price'] * df_data['num_item']
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0

In [251]:
df_data

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0
...,...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0,4.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0,2.0

What is the avgerage price of the three most expensive purchases?

In [252]:
#Write your code here
df_data.sort_values('total', ascending=False).head(3)['total'].mean()

# df_data.nlargest(3, 'total')['total'].mean()

np.float64(164.0)

How many different products are there?

In [253]:
#Write your code here
df_data['product_id'].nunique()

# df_data['product_id'].nunique()

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [254]:
#Write your code here
total_descr = df_data['total'].describe()
diff_total_mean_median = total_descr['mean'] - total_descr['50%']
diff_total_mean_median.round(4)

np.float64(0.9318)

Use the drop() method to delete the column total from the dataframe df_data.

In [255]:
#Write your code here
df_data.drop(columns=['total'], inplace=True)

Let's dig a little deeper into the data set and answer some basic question.

In [256]:
#Write your code here
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [257]:
#Write your code here
df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])
df_data['invoice_time'].dtype

/tmp/ipykernel_133947/1081537248.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_data['invoice_time'] = pd.to_datetime(df_data['invoice_time'])

dtype('<M8[ns]')

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [258]:
df_data['DOW'] = df_data['invoice_time'].dt.day_name()
df_data['Month'] = df_data['invoice_time'].dt.month

df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [259]:
#Write your code here
num_purchases_wed = df_data['DOW'].value_counts()['Wednesday']
num_purchases_wed

np.int64(959)

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [260]:
#Write your code here
df_titanic = pd.read_csv('Data/Titanic.csv')
df_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [261]:
#Write your code here
df_titanic = df_titanic.rename(columns={'Name':'Passenger_Name', 'Ticket':'Ticket_Num'})

df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [262]:
#Write your code here
df_titanic.set_index('PassengerId', inplace=True)

Select the name of passenger 896

In [263]:
#Write your code here
df_titanic.loc[896, 'Passenger_Name']

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [264]:
#Write your code here
df_titanic.reset_index(inplace=True)
df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [265]:
#Write you code here
df_titanic['Age'].isnull().sum()

np.int64(86)

Compute the avg age of passengers ignoring the missing data.

In [266]:
#Write your code here
age_avg = df_titanic['Age'].mean()

Using the fillna() method replace the missing values in the Age column with the mean.

In [267]:
#Write your code here
df_titanic['Age'] = df_titanic['Age'].fillna(age_avg)
df_titanic['Age'].isnull().sum()

np.int64(0)

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [ ]:
#Write your code here
df_titanic.sort_values('Age', ascending=False).head(5)['Age'].mean()

np.float64(67.0)