In [64]:
import pandas as pd

csv_path = r"H:\DEPI ENGBARAA\NumPy\Pandas\mall_orders_eda_demo.csv"
df = pd.read_csv(csv_path)
df

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,2025-15-01,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
1,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
2,ORD-1003,CUST-003,2025-12-03,Alexandria,21500,Mastercard,Clothing,low,2,5,60.0,1,15,420.0,22,"not good, size was wrong"
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good
5,ORD-1006,CUST-006,2025-12-06,Giza,12511,Cash,Groceries,low,1,20,70.0,2,0,180.0,19,terrible experience
6,ORD-1007,CUST-007,2025-12-07,Cairo,11765,Visa,Beauty,medium,4,2,95.0,2,25,320.0,31,Good value for money
7,ORD-1008,CUST-008,2025-12-08,Alexandria,21500,Mastercard,Toys,high,5,4,110.0,3,5,760.0,26,kids loved it
8,ORD-1009,CUST-009,2025-12-09,Giza,12511,NaN,Clothing,medium,3,6,80.0,2,10,530.0,23,NaN
9,ORD-1010,CUST-010,2025-12-10,Cairo,11765,Visa,Electronics,high,5,1,130.0,3,0,4800.0,-1,Perfect
10,ORD-1011,CUST-011,2025-12-11,New Cairo,11835,Cash,Home,low,2,2,150.0,4,5,NaN,45,Bad packaging
11,ORD-1012,CUST-012,2025-12-12,Alexandria,21500,Visa,Groceries,medium,3,8,65.0,1,0,410.0,28,average
12,ORD-1013,CUST-013,2025-12-13,Cairo,11765,Mastercard,Beauty,high,4,3,90.0,2,15,260.0,33,nice smell
13,ORD-1014,CUST-014,2025-12-14,Giza,12511,Visa,Toys,medium,3,1,105.0,3,0,300.0,17,ok
14,ORD-1015,CUST-015,2025-12-15,Alexandria,21500,Cash,Clothing,low,2,7,75.0,2,10,490.0,24,not worth it
15,ORD-1016,CUST-016,2025-12-16,Cairo,11765,Visa,Electronics,medium,4,2,125.0,3,5,5100.0,38,good
16,ORD-1017,CUST-017,2025-12-17,New Cairo,11835,Mastercard,Home,high,5,1,160.0,4,20,2400.0,29,Excellent quality
17,ORD-1018,CUST-018,2025-12-18,Giza,12511,Cash,Groceries,medium,3,15,68.0,1,0,220.0,36,fine
18,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
19,ORD-1019,CUST-019,2025-12-19,Cairo,11765,Visa,Beauty,NaN,4,2,92.0,2,10,310.0,30,good product

In [65]:
# fist look at the data (5 minutes overview)
df.head()
df.shape

df.columns
df.dtypes
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     object
 1   customer_id         20 non-null     object
 2   order_date          20 non-null     object
 3   city                20 non-null     object
 4   zip_code            20 non-null     int64
 5   payment_method      19 non-null     object
 6   product_category    20 non-null     object
 7   satisfaction_level  19 non-null     object
 8   rating              20 non-null     int64
 9   items_count         20 non-null     int64
 10  area_m2             20 non-null     float64
 11  rooms               20 non-null     int64
 12  discount_pct        20 non-null     int64
 13  total_price         19 non-null     float64
 14  age                 20 non-null     int64
 15  review_text         19 non-null     object
dtypes: float64(2), int64(6), object(8)
memory usage: 2.6+ KB

,zip_code,rating,items_count,area_m2,rooms,discount_pct,total_price,age
count,20.00000,20.000000,20.00000,20.000000,20.000000,20.000000,19.000000,20.000000
mean,13946.30000,3.500000,5.45000,105.275000,2.450000,7.250000,53963.105263,28.250000
std,3888.39909,1.192079,5.38492,36.725681,0.944513,7.340407,229099.782620,9.888191
min,11765.00000,1.000000,1.00000,60.000000,1.000000,0.000000,180.000000,-1.000000
25%,11765.00000,3.000000,2.00000,78.750000,2.000000,0.000000,315.000000,23.750000
50%,12173.00000,3.500000,3.00000,93.500000,2.000000,5.000000,530.000000,29.000000
75%,12511.00000,4.250000,7.25000,126.250000,3.000000,10.000000,2250.000000,34.000000
max,21500.00000,5.000000,20.00000,200.000000,4.000000,25.000000,999999.000000,45.000000

In [ ]:
df.describe() # only works on numerical columns

,order_date,rating,items_count,area_m2,rooms,discount_pct,total_price,age
count,19,20.000000,20.00000,20.000000,20.000000,20.000000,19.000000,20.000000
mean,2025-12-10 01:15:47.368421120,3.500000,5.45000,105.275000,2.450000,7.250000,53963.105263,28.250000
min,2025-12-02 00:00:00,1.000000,1.00000,60.000000,1.000000,0.000000,180.000000,-1.000000
25%,2025-12-05 12:00:00,3.000000,2.00000,78.750000,2.000000,0.000000,315.000000,23.750000
50%,2025-12-10 00:00:00,3.500000,3.00000,93.500000,2.000000,5.000000,530.000000,29.000000
75%,2025-12-14 12:00:00,4.250000,7.25000,126.250000,3.000000,10.000000,2250.000000,34.000000
max,2025-12-19 00:00:00,5.000000,20.00000,200.000000,4.000000,25.000000,999999.000000,45.000000
std,NaN,1.192079,5.38492,36.725681,0.944513,7.340407,229099.782620,9.888191

In [ ]:
#  total_price has some very high values 
# totoal_price needs further investigation
# age has some low values (less than 0)
# age needs further investigation
df[df["total_price"]> 2250]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,NaT,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
9,ORD-1010,CUST-010,2025-12-10,Cairo,11765,Visa,Electronics,high,5,1,130.0,3,0,4800.0,-1,Perfect
15,ORD-1016,CUST-016,2025-12-16,Cairo,11765,Visa,Electronics,medium,4,2,125.0,3,5,5100.0,38,good
16,ORD-1017,CUST-017,2025-12-17,New Cairo,11835,Mastercard,Home,high,5,1,160.0,4,20,2400.0,29,Excellent quality

In [ ]:
df.describe(include="all")  # works on all columns

In [66]:
df.head()

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,2025-15-01,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
1,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
2,ORD-1003,CUST-003,2025-12-03,Alexandria,21500,Mastercard,Clothing,low,2,5,60.0,1,15,420.0,22,"not good, size was wrong"
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good

In [67]:
df.sample(5,random_state=41)  # random 5 rows

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
10,ORD-1011,CUST-011,2025-12-11,New Cairo,11835,Cash,Home,low,2,2,150.0,4,5,NaN,45,Bad packaging
11,ORD-1012,CUST-012,2025-12-12,Alexandria,21500,Visa,Groceries,medium,3,8,65.0,1,0,410.0,28,average
14,ORD-1015,CUST-015,2025-12-15,Alexandria,21500,Cash,Clothing,low,2,7,75.0,2,10,490.0,24,not worth it
6,ORD-1007,CUST-007,2025-12-07,Cairo,11765,Visa,Beauty,medium,4,2,95.0,2,25,320.0,31,Good value for money
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good

In [68]:
df.shape

(20, 16)

In [69]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'city', 'zip_code',
       'payment_method', 'product_category', 'satisfaction_level', 'rating',
       'items_count', 'area_m2', 'rooms', 'discount_pct', 'total_price', 'age',
       'review_text'],
      dtype='object')

In [70]:
df.dtypes  # data types of each column
# object  -> string
# int64   -> integer numbers
# float64 -> decimal numbers

order_id               object
customer_id            object
order_date             object
city                   object
zip_code                int64
payment_method         object
product_category       object
satisfaction_level     object
rating                  int64
items_count             int64
area_m2               float64
rooms                   int64
discount_pct            int64
total_price           float64
age                     int64
review_text            object
dtype: object

In [71]:
df.info() # summary of the dataframe
# non-null count, memory usage, data types
# useful for large datasets with missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     object
 1   customer_id         20 non-null     object
 2   order_date          20 non-null     object
 3   city                20 non-null     object
 4   zip_code            20 non-null     int64
 5   payment_method      19 non-null     object
 6   product_category    20 non-null     object
 7   satisfaction_level  19 non-null     object
 8   rating              20 non-null     int64
 9   items_count         20 non-null     int64
 10  area_m2             20 non-null     float64
 11  rooms               20 non-null     int64
 12  discount_pct        20 non-null     int64
 13  total_price         19 non-null     float64
 14  age                 20 non-null     int64
 15  review_text         19 non-null     object
dtypes: float64(2), int64(6), object(8)
memory usage: 2.6+ KB

In [72]:
df.head()

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,2025-15-01,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
1,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
2,ORD-1003,CUST-003,2025-12-03,Alexandria,21500,Mastercard,Clothing,low,2,5,60.0,1,15,420.0,22,"not good, size was wrong"
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good

In [73]:
df[["order_date", "order_id"]].head()

   order_date  order_id
0  2025-15-01  ORD-1001
1  2025-12-02  ORD-1002
2  2025-12-03  ORD-1003
3  2025-12-04  ORD-1004
4  2025-12-05  ORD-1005

In [74]:
df["order_date"].head()

0    2025-15-01
1    2025-12-02
2    2025-12-03
3    2025-12-04
4    2025-12-05
Name: order_date, dtype: object

In [75]:
#  convert to datetime type
df['order_date'] = pd.to_datetime(df['order_date'],errors='coerce')

C:\Users\baraa\AppData\Local\Temp\ipykernel_28124\2108352468.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['order_date'] = pd.to_datetime(df['order_date'],errors='coerce')

In [76]:
df["order_date"].head()

0          NaT
1   2025-12-02
2   2025-12-03
3   2025-12-04
4   2025-12-05
Name: order_date, dtype: datetime64[ns]

In [77]:
df.head()

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,NaT,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
1,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
2,ORD-1003,CUST-003,2025-12-03,Alexandria,21500,Mastercard,Clothing,low,2,5,60.0,1,15,420.0,22,"not good, size was wrong"
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     object
 1   customer_id         20 non-null     object
 2   order_date          19 non-null     datetime64[ns]
 3   city                20 non-null     object
 4   zip_code            20 non-null     int64
 5   payment_method      19 non-null     object
 6   product_category    20 non-null     object
 7   satisfaction_level  19 non-null     object
 8   rating              20 non-null     int64
 9   items_count         20 non-null     int64
 10  area_m2             20 non-null     float64
 11  rooms               20 non-null     int64
 12  discount_pct        20 non-null     int64
 13  total_price         19 non-null     float64
 14  age                 20 non-null     int64
 15  review_text         19 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(6), object(7)
memory usage: 2.6+ KB

In [79]:
# order_date have missing data ( NaT ) because of wrong date format in the csv file

In [80]:
df["city"].value_counts() # only for categorical columns

city
Cairo         7
Giza          6
Alexandria    4
New Cairo     3
Name: count, dtype: int64

In [81]:
df["zip_code"].value_counts()
# need to covrt zip_code to object type
df["zip_code"] = df["zip_code"].astype("object")
df["zip_code"].value_counts()

zip_code
11765    7
12511    6
21500    4
11835    3
Name: count, dtype: int64

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     object
 1   customer_id         20 non-null     object
 2   order_date          19 non-null     datetime64[ns]
 3   city                20 non-null     object
 4   zip_code            20 non-null     object
 5   payment_method      19 non-null     object
 6   product_category    20 non-null     object
 7   satisfaction_level  19 non-null     object
 8   rating              20 non-null     int64
 9   items_count         20 non-null     int64
 10  area_m2             20 non-null     float64
 11  rooms               20 non-null     int64
 12  discount_pct        20 non-null     int64
 13  total_price         19 non-null     float64
 14  age                 20 non-null     int64
 15  review_text         19 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(5), object(8)
memory usage: 2.6+ KB

In [83]:
df["payment_method"].value_counts(normalize=True,dropna=False)  # percentage

payment_method
Visa          0.45
Cash          0.30
Mastercard    0.20
NaN           0.05
Name: proportion, dtype: float64

In [84]:
df["payment_method"].value_counts(dropna=False) # include NaN in the counts

payment_method
Visa          9
Cash          6
Mastercard    4
NaN           1
Name: count, dtype: int64

In [85]:
df[df["payment_method"].isna()]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
8,ORD-1009,CUST-009,2025-12-09,Giza,12511,NaN,Clothing,medium,3,6,80.0,2,10,530.0,23,NaN

In [86]:
df[df["payment_method"].isna()].index

Index([8], dtype='int64')

In [58]:
# Options:
# 1: Drop rows with missing payment_method
df_cleaned = df.dropna(subset=["payment_method"])
df_cleaned

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,NaT,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
1,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
2,ORD-1003,CUST-003,2025-12-03,Alexandria,21500,Mastercard,Clothing,low,2,5,60.0,1,15,420.0,22,"not good, size was wrong"
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good
5,ORD-1006,CUST-006,2025-12-06,Giza,12511,Cash,Groceries,low,1,20,70.0,2,0,180.0,19,terrible experience
6,ORD-1007,CUST-007,2025-12-07,Cairo,11765,Visa,Beauty,medium,4,2,95.0,2,25,320.0,31,Good value for money
7,ORD-1008,CUST-008,2025-12-08,Alexandria,21500,Mastercard,Toys,high,5,4,110.0,3,5,760.0,26,kids loved it
9,ORD-1010,CUST-010,2025-12-10,Cairo,11765,Visa,Electronics,high,5,1,130.0,3,0,4800.0,-1,Perfect
10,ORD-1011,CUST-011,2025-12-11,New Cairo,11835,Cash,Home,low,2,2,150.0,4,5,NaN,45,Bad packaging
11,ORD-1012,CUST-012,2025-12-12,Alexandria,21500,Visa,Groceries,medium,3,8,65.0,1,0,410.0,28,average
12,ORD-1013,CUST-013,2025-12-13,Cairo,11765,Mastercard,Beauty,high,4,3,90.0,2,15,260.0,33,nice smell
13,ORD-1014,CUST-014,2025-12-14,Giza,12511,Visa,Toys,medium,3,1,105.0,3,0,300.0,17,ok
14,ORD-1015,CUST-015,2025-12-15,Alexandria,21500,Cash,Clothing,low,2,7,75.0,2,10,490.0,24,not worth it
15,ORD-1016,CUST-016,2025-12-16,Cairo,11765,Visa,Electronics,medium,4,2,125.0,3,5,5100.0,38,good
16,ORD-1017,CUST-017,2025-12-17,New Cairo,11835,Mastercard,Home,high,5,1,160.0,4,20,2400.0,29,Excellent quality
17,ORD-1018,CUST-018,2025-12-18,Giza,12511,Cash,Groceries,medium,3,15,68.0,1,0,220.0,36,fine
18,ORD-1002,CUST-002,2025-12-02,Giza,12511,Cash,Groceries,medium,3,12,85.0,2,0,650.0,34,"okay quality, nothing special"
19,ORD-1019,CUST-019,2025-12-19,Cairo,11765,Visa,Beauty,NaN,4,2,92.0,2,10,310.0,30,good product

In [59]:
df[df["payment_method"].isna()]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
8,ORD-1009,CUST-009,2025-12-09,Giza,12511,NaN,Clothing,medium,3,6,80.0,2,10,530.0,23,NaN

In [89]:
df["payment_method"].mode()[0]

'Visa'

In [90]:
# 2: Fill missing payment_method with 'Unknown'
#df["payment_method"] = df["payment_method"].fillna("Unknown")
df["payment_method"] = df["payment_method"].fillna(  
    df["payment_method"].mode()[0]  # most frequent value    
)

In [91]:
df[df["payment_method"].isna() ]

Empty DataFrame
Columns: [order_id, customer_id, order_date, city, zip_code, payment_method, product_category, satisfaction_level, rating, items_count, area_m2, rooms, discount_pct, total_price, age, review_text]
Index: []

In [92]:
df["payment_method"]

0           Visa
1           Cash
2     Mastercard
3           Visa
4           Visa
5           Cash
6           Visa
7     Mastercard
8           Visa
9           Visa
10          Cash
11          Visa
12    Mastercard
13          Visa
14          Cash
15          Visa
16    Mastercard
17          Cash
18          Cash
19          Visa
Name: payment_method, dtype: object

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            20 non-null     object
 1   customer_id         20 non-null     object
 2   order_date          19 non-null     datetime64[ns]
 3   city                20 non-null     object
 4   zip_code            20 non-null     object
 5   payment_method      20 non-null     object
 6   product_category    20 non-null     object
 7   satisfaction_level  19 non-null     object
 8   rating              20 non-null     int64
 9   items_count         20 non-null     int64
 10  area_m2             20 non-null     float64
 11  rooms               20 non-null     int64
 12  discount_pct        20 non-null     int64
 13  total_price         19 non-null     float64
 14  age                 20 non-null     int64
 15  review_text         19 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(5), object(8)
memory usage: 2.6+ KB

In [95]:
df[df["total_price"]> 2000]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
0,ORD-1001,CUST-001,NaT,Cairo,11765,Visa,Electronics,high,5,2,120.5,3,10,5400.0,29,Great service and fast delivery
3,ORD-1004,CUST-004,2025-12-04,Cairo,11765,Visa,Electronics,high,5,1,200.0,4,5,999999.0,41,Excellent! will buy again
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good
9,ORD-1010,CUST-010,2025-12-10,Cairo,11765,Visa,Electronics,high,5,1,130.0,3,0,4800.0,-1,Perfect
15,ORD-1016,CUST-016,2025-12-16,Cairo,11765,Visa,Electronics,medium,4,2,125.0,3,5,5100.0,38,good
16,ORD-1017,CUST-017,2025-12-17,New Cairo,11835,Mastercard,Home,high,5,1,160.0,4,20,2400.0,29,Excellent quality

In [98]:
df[df["city"]== "New Cairo"]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good
10,ORD-1011,CUST-011,2025-12-11,New Cairo,11835,Cash,Home,low,2,2,150.0,4,5,NaN,45,Bad packaging
16,ORD-1017,CUST-017,2025-12-17,New Cairo,11835,Mastercard,Home,high,5,1,160.0,4,20,2400.0,29,Excellent quality

In [ ]:
df[  (df["city"]== "New Cairo") & (df["payment_method"]=="Visa") ]

,order_id,customer_id,order_date,city,zip_code,payment_method,product_category,satisfaction_level,rating,items_count,area_m2,rooms,discount_pct,total_price,age,review_text
4,ORD-1005,CUST-005,2025-12-05,New Cairo,11835,Visa,Home,medium,4,3,140.0,3,10,2100.0,27,Delivery was late but product is good

In [102]:
df[["city","total_price"]]

          city  total_price
0        Cairo       5400.0
1         Giza        650.0
2   Alexandria        420.0
3        Cairo     999999.0
4    New Cairo       2100.0
5         Giza        180.0
6        Cairo        320.0
7   Alexandria        760.0
8         Giza        530.0
9        Cairo       4800.0
10   New Cairo          NaN
11  Alexandria        410.0
12       Cairo        260.0
13        Giza        300.0
14  Alexandria        490.0
15       Cairo       5100.0
16   New Cairo       2400.0
17        Giza        220.0
18        Giza        650.0
19       Cairo        310.0

In [ ]:
df.groupby("city")["total_price"].median()
# why median not mean?
# because of outliers in total_price
# total_price needs further investigation

city
Alexandria     455.0
Cairo         4800.0
Giza           415.0
New Cairo     2250.0
Name: total_price, dtype: float64

In [105]:
df["product_category"].value_counts()

product_category
Groceries      5
Electronics    4
Clothing       3
Home           3
Beauty         3
Toys           2
Name: count, dtype: int64

In [107]:
df.describe()

,order_date,rating,items_count,area_m2,rooms,discount_pct,total_price,age
count,19,20.000000,20.00000,20.000000,20.000000,20.000000,19.000000,20.000000
mean,2025-12-10 01:15:47.368421120,3.500000,5.45000,105.275000,2.450000,7.250000,53963.105263,28.250000
min,2025-12-02 00:00:00,1.000000,1.00000,60.000000,1.000000,0.000000,180.000000,-1.000000
25%,2025-12-05 12:00:00,3.000000,2.00000,78.750000,2.000000,0.000000,315.000000,23.750000
50%,2025-12-10 00:00:00,3.500000,3.00000,93.500000,2.000000,5.000000,530.000000,29.000000
75%,2025-12-14 12:00:00,4.250000,7.25000,126.250000,3.000000,10.000000,2250.000000,34.000000
max,2025-12-19 00:00:00,5.000000,20.00000,200.000000,4.000000,25.000000,999999.000000,45.000000
std,NaN,1.192079,5.38492,36.725681,0.944513,7.340407,229099.782620,9.888191

In [106]:
df.groupby("product_category")["rating"].mean()

product_category
Beauty         4.000000
Clothing       2.333333
Electronics    4.750000
Groceries      2.600000
Home           3.666667
Toys           4.000000
Name: rating, dtype: float64

In [110]:
df.groupby("product_category")["rating"].mean().sort_values(ascending=False)

product_category
Electronics    4.750000
Beauty         4.000000
Toys           4.000000
Home           3.666667
Groceries      2.600000
Clothing       2.333333
Name: rating, dtype: float64