# Data Cleaning or Cleansing

Whenever we have to work with a real world dataset, the first problem that we face is to clean it. The real world dataset never comes clean. It consists lot of discrepancies in the dataset. So, we have to clean the dataset for further processing.

Cleaning data is the process of preparing the dataset for analysis. It is very important because the accuracy of machine learning or data mining models are affected because of poor quality of data.

So, data scientists spend a large amount of their time cleaning the dataset and transform them into a format with which they can work with. In fact, data scientists spend 80% of their time cleaning the data.

A very common scenario is that the dataset contains missing values coded as NaN. Also, the missing values are coded in different ways. The dataset may contain negative or invalid values. It may contain outliers. It may be in the untidy format. All of these are examples of a messy dataset.

In this project, I present several useful ways to handle these discrepancies in the dataset.

## 1) Import the required Python libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
sns.set(rc={'figure.figsize': [10, 10]}, font_scale=1.3)

## 2) Read Data

In [3]:
df = pd.read_csv('datasets/friends.csv', sep='|')

In [4]:
df

,fname,lname,age_sex,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C
0,Rahul,Pandey,37_M,B,175.4,85.6,37,1500.0,200.0,300
1,Rakesh,Kumar,38_M,B,NaN,xx,38,NaN,1000.0,NaN
2,Nitesh,Mondol,35_F,B,165.1,?,35,500.0,-100.0,200
3,Arvind,Dwivedi,40_M,A,0,55.6,40,300.0,300.0,NaN
4,Nikhil,Shikharwar,39_M,B,160.8,160,39,200.0,NaN,300
5,Ashutosh,Merothiya,36_M,A,xx,-60,36,100.0,400.0,NaN
6,Shubhro,Das,35_F,C,170.3,75.5,35,NaN,500.0,500
7,Suvendu,Das,34_M,C,155.1,56.8,34,1000.0,100.0,xx
8,Swadesh,Kumar,36_M,?,154.2,60.6,36,100.0,200.0,300
9,Arun,Vishwakarma,38_F,A,162.1,58.7,38,600.0,200.0,200

In [42]:
df.info() # old info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   age_sex     10 non-null     object
 3   section     10 non-null     object
 4   height(cm)  9 non-null      object
 5   weight(kg)  10 non-null     object
 6   age         10 non-null     int64
 7   spend_A     8 non-null      float64
 8   spend_B     9 non-null      float64
 9   spend_C     7 non-null      object
dtypes: float64(2), int64(1), object(7)
memory usage: 932.0+ bytes

In [44]:
df.describe()

             age      spend_A      spend_B
count  10.000000     8.000000     9.000000
mean   36.800000   537.500000   311.111111
std     1.932184   492.624169   310.017921
min    34.000000   100.000000  -100.000000
25%    35.250000   175.000000   200.000000
50%    36.500000   400.000000   200.000000
75%    38.000000   700.000000   400.000000
max    40.000000  1500.000000  1000.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   age_sex     10 non-null     object
 3   section     10 non-null     object
 4   height(cm)  9 non-null      object
 5   weight(kg)  10 non-null     object
 6   age         10 non-null     int64
 7   spend_A     8 non-null      float64
 8   spend_B     9 non-null      float64
 9   spend_C     7 non-null      object
dtypes: float64(2), int64(1), object(7)
memory usage: 932.0+ bytes

In [36]:
df.describe()

             age      spend_A      spend_B
count  10.000000     8.000000     9.000000
mean   36.800000   537.500000   311.111111
std     1.932184   492.624169   310.017921
min    34.000000   100.000000  -100.000000
25%    35.250000   175.000000   200.000000
50%    36.500000   400.000000   200.000000
75%    38.000000   700.000000   400.000000
max    40.000000  1500.000000  1000.000000

**Some feature engineering**

In [9]:
age_sex = "37_M"
age_sex.split("_")

['37', 'M']

In [39]:
age_sex.split("_")[-1]

'M'

In [38]:
df['sex'] = df['age_sex'].apply(lambda x: x.split('_')[-1])
df.head(10)

,fname,lname,age_sex,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,Rahul,Pandey,37_M,B,175.4,85.6,37,1500.0,200.0,300,M
1,Rakesh,Kumar,38_M,B,NaN,xx,38,NaN,1000.0,NaN,M
2,Nitesh,Mondol,35_F,B,165.1,?,35,500.0,-100.0,200,F
3,Arvind,Dwivedi,40_M,A,0,55.6,40,300.0,300.0,NaN,M
4,Nikhil,Shikharwar,39_M,B,160.8,160,39,200.0,NaN,300,M
5,Ashutosh,Merothiya,36_M,A,xx,-60,36,100.0,400.0,NaN,M
6,Shubhro,Das,35_F,C,170.3,75.5,35,NaN,500.0,500,F
7,Suvendu,Das,34_M,C,155.1,56.8,34,1000.0,100.0,xx,M
8,Swadesh,Kumar,36_M,?,154.2,60.6,36,100.0,200.0,300,M
9,Arun,Vishwakarma,38_F,A,162.1,58.7,38,600.0,200.0,200,F

In [39]:
df.drop('age_sex', axis=1, inplace=True)
df.head(10)

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,Rahul,Pandey,B,175.4,85.6,37,1500.0,200.0,300,M
1,Rakesh,Kumar,B,NaN,xx,38,NaN,1000.0,NaN,M
2,Nitesh,Mondol,B,165.1,?,35,500.0,-100.0,200,F
3,Arvind,Dwivedi,A,0,55.6,40,300.0,300.0,NaN,M
4,Nikhil,Shikharwar,B,160.8,160,39,200.0,NaN,300,M
5,Ashutosh,Merothiya,A,xx,-60,36,100.0,400.0,NaN,M
6,Shubhro,Das,C,170.3,75.5,35,NaN,500.0,500,F
7,Suvendu,Das,C,155.1,56.8,34,1000.0,100.0,xx,M
8,Swadesh,Kumar,?,154.2,60.6,36,100.0,200.0,300,M
9,Arun,Vishwakarma,A,162.1,58.7,38,600.0,200.0,200,F

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   section     10 non-null     object
 3   height(cm)  9 non-null      object
 4   weight(kg)  10 non-null     object
 5   age         10 non-null     int64
 6   spend_A     8 non-null      float64
 7   spend_B     9 non-null      float64
 8   spend_C     7 non-null      object
 9   sex         10 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 932.0+ bytes

In [41]:
df.describe()

             age      spend_A      spend_B
count  10.000000     8.000000     9.000000
mean   36.800000   537.500000   311.111111
std     1.932184   492.624169   310.017921
min    34.000000   100.000000  -100.000000
25%    35.250000   175.000000   200.000000
50%    36.500000   400.000000   200.000000
75%    38.000000   700.000000   400.000000
max    40.000000  1500.000000  1000.000000

**Problems**
- Weight, height, spend_C are not shown in describe because they are not numeric

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   section     10 non-null     object
 3   height(cm)  9 non-null      object
 4   weight(kg)  10 non-null     object
 5   age         10 non-null     int64
 6   spend_A     8 non-null      float64
 7   spend_B     9 non-null      float64
 8   spend_C     7 non-null      object
 9   sex         10 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 932.0+ bytes

## 3) Start Cleaning

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   section     10 non-null     object
 3   height(cm)  9 non-null      object
 4   weight(kg)  10 non-null     object
 5   age         10 non-null     int64
 6   spend_A     8 non-null      float64
 7   spend_B     9 non-null      float64
 8   spend_C     7 non-null      object
 9   sex         10 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 932.0+ bytes

In [47]:
df.head(10)

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,Rahul,Pandey,B,175.4,85.6,37,1500.0,200.0,300,M
1,Rakesh,Kumar,B,NaN,xx,38,NaN,1000.0,NaN,M
2,Nitesh,Mondol,B,165.1,?,35,500.0,-100.0,200,F
3,Arvind,Dwivedi,A,0,55.6,40,300.0,300.0,NaN,M
4,Nikhil,Shikharwar,B,160.8,160,39,200.0,NaN,300,M
5,Ashutosh,Merothiya,A,xx,-60,36,100.0,400.0,NaN,M
6,Shubhro,Das,C,170.3,75.5,35,NaN,500.0,500,F
7,Suvendu,Das,C,155.1,56.8,34,1000.0,100.0,xx,M
8,Swadesh,Kumar,?,154.2,60.6,36,100.0,200.0,300,M
9,Arun,Vishwakarma,A,162.1,58.7,38,600.0,200.0,200,F

first start with changing columns data type for the right one and using **errors='coerce'** you will be sure any data that not in format will be NaN

In [50]:
 df["height(cm)"]= pd.to_numeric(df["height(cm)"], errors='coerce')
df["weight(kg)"] = pd.to_numeric(df["weight(kg)"], errors='coerce')
df["spend_C"] = pd.to_numeric(df["spend_C"], errors='coerce')

In [52]:
numerical_colms = ['height(cm)', 'weight(kg)', 'spend_C']

for col in numerical_colms:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [56]:
df.head(10)

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,Rahul,Pandey,B,175.4,85.6,37,1500.0,200.0,300.0,M
1,Rakesh,Kumar,B,NaN,NaN,38,NaN,1000.0,NaN,M
2,Nitesh,Mondol,B,165.1,NaN,35,500.0,-100.0,200.0,F
3,Arvind,Dwivedi,A,0.0,55.6,40,300.0,300.0,NaN,M
4,Nikhil,Shikharwar,B,160.8,160.0,39,200.0,NaN,300.0,M
5,Ashutosh,Merothiya,A,NaN,-60.0,36,100.0,400.0,NaN,M
6,Shubhro,Das,C,170.3,75.5,35,NaN,500.0,500.0,F
7,Suvendu,Das,C,155.1,56.8,34,1000.0,100.0,NaN,M
8,Swadesh,Kumar,?,154.2,60.6,36,100.0,200.0,300.0,M
9,Arun,Vishwakarma,A,162.1,58.7,38,600.0,200.0,200.0,F

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   section     10 non-null     object
 3   height(cm)  8 non-null      float64
 4   weight(kg)  8 non-null      float64
 5   age         10 non-null     int64
 6   spend_A     8 non-null      float64
 7   spend_B     9 non-null      float64
 8   spend_C     6 non-null      float64
 9   sex         10 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 932.0+ bytes

In [59]:
df.describe()

       height(cm)  weight(kg)        age      spend_A      spend_B     spend_C
count      8.0000    8.000000  10.000000     8.000000     9.000000    6.000000
mean     142.8750   61.600000  36.800000   537.500000   311.111111  300.000000
std       58.1695   60.126985   1.932184   492.624169   310.017921  109.544512
min        0.0000  -60.000000  34.000000   100.000000  -100.000000  200.000000
25%      154.8750   56.500000  35.250000   175.000000   200.000000  225.000000
50%      161.4500   59.650000  36.500000   400.000000   200.000000  300.000000
75%      166.4000   78.025000  38.000000   700.000000   400.000000  300.000000
max      175.4000  160.000000  40.000000  1500.000000  1000.000000  500.000000

**Problems**
- Weight column has -60 kg and that's wrong.
- Height column has min value of 0 and that's wrong also.
- Spend_B columns has min value of -100 that make no sense.

In [63]:
df[df['weight(kg)'] < 10]

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
5,Ashutosh,Merothiya,A,NaN,-60.0,36,100.0,400.0,NaN,M

In [65]:
df[df['spend_B'] < 0]

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
2,Nitesh,Mondol,B,165.1,NaN,35,500.0,-100.0,200.0,F

In [66]:
df['weight(kg)'] = df['weight(kg)'].apply(lambda x: abs(x))
df['spend_B'] = df['spend_B'].apply(lambda x: abs(x))

In [73]:
df.describe()

       height(cm)  weight(kg)        age      spend_A      spend_B     spend_C
count      8.0000    8.000000  10.000000     8.000000     9.000000    6.000000
mean     142.8750   76.600000  36.800000   537.500000   333.333333  300.000000
std       58.1695   35.300304   1.932184   492.624169   282.842712  109.544512
min        0.0000   55.600000  34.000000   100.000000   100.000000  200.000000
25%      154.8750   58.225000  35.250000   175.000000   200.000000  225.000000
50%      161.4500   60.300000  36.500000   400.000000   200.000000  300.000000
75%      166.4000   78.025000  38.000000   700.000000   400.000000  300.000000
max      175.4000  160.000000  40.000000  1500.000000  1000.000000  500.000000

In [75]:
df[df['height(cm)'] < 100]

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
3,Arvind,Dwivedi,A,0.0,55.6,40,300.0,300.0,NaN,M

In [76]:
median_of_height = df['height(cm)'].median()
median_of_height

161.45

In [79]:
df[df['height(cm)'] < 100]['height(cm)'] = median_of_height

C:\Users\Baraa\AppData\Local\Temp\ipykernel_4416\757112962.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['height(cm)'] < 100]['height(cm)'] = median_of_height

In [80]:
df.describe()

       height(cm)  weight(kg)        age      spend_A      spend_B     spend_C
count      8.0000    8.000000  10.000000     8.000000     9.000000    6.000000
mean     142.8750   76.600000  36.800000   537.500000   333.333333  300.000000
std       58.1695   35.300304   1.932184   492.624169   282.842712  109.544512
min        0.0000   55.600000  34.000000   100.000000   100.000000  200.000000
25%      154.8750   58.225000  35.250000   175.000000   200.000000  225.000000
50%      161.4500   60.300000  36.500000   400.000000   200.000000  300.000000
75%      166.4000   78.025000  38.000000   700.000000   400.000000  300.000000
max      175.4000  160.000000  40.000000  1500.000000  1000.000000  500.000000

In [81]:
df.loc[df['height(cm)'] < 100, 'height(cm)'] = median_of_height
df.head(10)

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex
0,Rahul,Pandey,B,175.40,85.6,37,1500.0,200.0,300.0,M
1,Rakesh,Kumar,B,NaN,NaN,38,NaN,1000.0,NaN,M
2,Nitesh,Mondol,B,165.10,NaN,35,500.0,100.0,200.0,F
3,Arvind,Dwivedi,A,161.45,55.6,40,300.0,300.0,NaN,M
4,Nikhil,Shikharwar,B,160.80,160.0,39,200.0,NaN,300.0,M
5,Ashutosh,Merothiya,A,NaN,60.0,36,100.0,400.0,NaN,M
6,Shubhro,Das,C,170.30,75.5,35,NaN,500.0,500.0,F
7,Suvendu,Das,C,155.10,56.8,34,1000.0,100.0,NaN,M
8,Swadesh,Kumar,?,154.20,60.6,36,100.0,200.0,300.0,M
9,Arun,Vishwakarma,A,162.10,58.7,38,600.0,200.0,200.0,F

In [82]:
df.describe()

       height(cm)  weight(kg)        age      spend_A      spend_B     spend_C
count    8.000000    8.000000  10.000000     8.000000     9.000000    6.000000
mean   163.056250   76.600000  36.800000   537.500000   333.333333  300.000000
std      7.164767   35.300304   1.932184   492.624169   282.842712  109.544512
min    154.200000   55.600000  34.000000   100.000000   100.000000  200.000000
25%    159.375000   58.225000  35.250000   175.000000   200.000000  225.000000
50%    161.775000   60.300000  36.500000   400.000000   200.000000  300.000000
75%    166.400000   78.025000  38.000000   700.000000   400.000000  300.000000
max    175.400000  160.000000  40.000000  1500.000000  1000.000000  500.000000

In [83]:
# Method using apply
# def non_zero_height(x):
#     if x < 100:
#         return median_of_height
#     else:
#         return x

# df['height(cm)'] = df['height(cm)'].apply(non_zero_height)
# df['height(cm)'] = df['height(cm)'].apply(lambda x: median_of_height if x < 100 else x)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   fname       10 non-null     object
 1   lname       10 non-null     object
 2   section     10 non-null     object
 3   height(cm)  8 non-null      float64
 4   weight(kg)  8 non-null      float64
 5   age         10 non-null     int64
 6   spend_A     8 non-null      float64
 7   spend_B     9 non-null      float64
 8   spend_C     6 non-null      float64
 9   sex         10 non-null     object
dtypes: float64(5), int64(1), object(4)
memory usage: 932.0+ bytes

In [85]:
df['section'].unique()

array(['B', 'A', 'C', '?'], dtype=object)

In [87]:
df['section'].value_counts()

section
B    4
A    3
C    2
?    1
Name: count, dtype: int64

In [88]:
df['section'].mode()[0]

'B'

In [97]:
df['section'] = df['section'].apply(lambda x: df['section'].mode()[0] if x == '?' else x)

In [99]:
df['section'].unique()

array(['B', 'A', 'C'], dtype=object)

In [101]:
df['section'].value_counts()

section
B    5
A    3
C    2
Name: count, dtype: int64

In [102]:
df['sex'].unique()

array(['M', 'F'], dtype=object)

In [103]:
df['sex'].value_counts()

sex
M    7
F    3
Name: count, dtype: int64

# Great Work!

In [75]:
from sklearn.preprocessing import LabelEncoder

In [79]:
encoder = LabelEncoder()

In [85]:
df['encoded_section'] = encoder.fit_transform(df['section'])

In [87]:
df

,fname,lname,section,height(cm),weight(kg),age,spend_A,spend_B,spend_C,sex,encoded_section
0,Rahul,Pandey,B,175.400,85.60,37,1500.0,200.000000,300.0,M,1
1,Rakesh,Kumar,B,167.700,68.55,38,300.0,1000.000000,350.0,M,1
2,Nitesh,Mondol,B,165.100,57.15,35,500.0,311.111111,200.0,F,1
3,Arvind,Dwivedi,A,142.875,55.60,40,300.0,300.000000,300.0,M,0
4,Nikhil,Shikharwar,B,160.800,160.00,39,200.0,250.000000,300.0,M,1
5,Ashutosh,Merothiya,A,165.550,61.60,36,100.0,400.000000,400.0,M,0
6,Shubhro,Das,C,170.300,75.50,35,200.0,500.000000,500.0,F,2
7,Suvendu,Das,C,155.100,56.80,34,1000.0,100.000000,350.0,M,2
8,Swadesh,Kumar,B,154.200,60.60,36,100.0,200.000000,300.0,M,1
9,Arun,Vishwakarma,A,162.100,58.70,38,600.0,200.000000,200.0,F,0